name: Releases
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Generate standard x86_64 iso
        run: |
          ./generate_bootable_iso.sh standard x86_64
      - name: Generate extended x86_64 iso
        run: |
          ./generate_bootable_iso.sh extended x86_64
      - name: Compress
        run: |
          cp iso_output/* . &&
          gzip -9 alpine-frozenkrill_standard-edge-x86_64.iso &&
          gzip -9 alpine-frozenkrill_extended-edge-x86_64.iso
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "alpine-frozenkrill_standard-edge-x86_64.iso.gz,alpine-frozenkrill_extended-edge-x86_64.iso.gz"
          bodyFile: "Release.md"
          draft: true
          prerelease: true
